from tkinter import*
window=Tk()
window.title("Besant Technologies")
Label(window, text='Besant technologies\n Enquiry Form').grid(row=0,column=1)
Label(window, text='Date:').grid(row=1,column=0,sticky="w")
Label(window, text='Name:').grid (row=2,column=0,sticky="w")
Label(window, text='Mobile-No:').grid(row=3,column=0,sticky="w")
Label(window, text='Email-id:').grid(row=4,column=0,sticky="w")
Label(window, text='Address:').grid(row=5,column=0,sticky="w")
Label(window, text='Course intersted:').grid(row=6,column=0,sticky="w")
Label(window, text='Batch preferred:').grid(row=7,column=0,sticky="w")
Label(window, text='How you came to know Us:').grid(row=8,column=0,sticky="w")
Label(window, text='Are you Experience or Fresher:').grid(row=9,column=0,sticky="w")
Label(window, text='Contact person From Besant Technologies:').grid(row=10,column=0,sticky="w")
Label(window, text='Counselor:').grid(row=11,column=0,sticky="w")
Label(window, text='Fees:').grid(row=12,column=0,sticky="w")
Label(window, text='Comment:').grid(row=13,column=0,sticky="w")
Date=Entry (window,width=50)            
Name=Entry(window,width=50)
MobileNo=Entry(window,width=50)
Emailid=Entry(window,width=50)
Address=Entry(window,width=50)
Courseintersted=Entry(window,width=50)
Batchperferred=Entry(window,width=50)
HowyoucametoknowUs=Entry(window,width=50)
AreyouExperienceorFresher=Entry(window,width=50)
ContactpersonFromBesantTechnologies=Entry(window,width=50)
Conselor=Entry(window,width=50)
Fees=Entry(window,width=50)
Comment=Entry(window,width=50)
Date.grid(row=1,column=1)
Name.grid(row=2,column=1)
MobileNo.grid(row=3,column=1)
Emailid.grid(row=4,column=1)
Address.grid(row=5,column=1)
Courseintersted.grid(row=6,column=1)
Batchperferred.grid(row=7,column=1)
HowyoucametoknowUs.grid(row=8,column=1)
AreyouExperienceorFresher.grid(row=9,column=1)
ContactpersonFromBesantTechnologies.grid(row=10,column=1)
Conselor.grid(row=11,column=1)
Fees.grid(row=12,column=1)
Comment.grid(row=13,column=1)
varReg=IntVar()
varEnqui=IntVar()
checkbox1=Checkbutton(window,text="registration",variable=varReg,onvalue=1,offvalue=0,height=2,width=10).place(x=400,y=350)
checkbox2=Checkbutton(window,text="Enquiry",variable=varEnqui,onvalue=1,offvalue=0,height=2,width=10).place(x=230,y=350)
button1=Button(window,text='submit',width=10,bg="green").place(x=230,y=400)
button2=Button(window,text='cancel',width=10,bg="red").place(x=400,y=400)
mainloop()
